apiVersion: apps/v1
kind: Deployment
metadata:
  name: kids-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kids-api
  template:
    metadata:
      labels:
        app: kids-api
    spec:
      containers:
      - name: kids-api
        image: eduhass/kids-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        envFrom:
        - configMapRef:
            name: kids-api-config
        - secretRef:
            name: kids-api-secrets