apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- postgresql.yaml
- postgres-backup-pvc.yaml
- postgres-backup-job.yaml
- postgres-init-script.yaml

labels:
- pairs:
    app: kids-api

images:
- name: eduhass/kids-api
  newTag: latest 

secretGenerator:
- name: postgres-secret
  literals:
  - POSTGRES_USER=kidsuser
  - POSTGRES_PASSWORD=kidssecret
  - POSTGRES_DB=kidsdb
- name: kids-api-secrets
  literals:
  - AUTH0_DOMAIN=dev-tenant.auth0.com
  - AUTH0_AUDIENCE=https://dev-api.kids.com
  - DATABASE_URL=postgres://kidsuser:kidssecret@postgres:5432/kidsdb?sslmode=disable