apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- postgresql.yaml
- postgres-backup-pvc.yaml
- postgres-backup-job.yaml

commonLabels:
  app: kids-api

secretGenerator:
- name: postgres-secret
  literals:
  - POSTGRES_USER=kidsuser
  - POSTGRES_PASSWORD=kidssecret
  - POSTGRES_DB=kidsdb