apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-backup
spec:
  template:
    spec:
      containers:
      - name: backup
        image: postgres:15-alpine
        command: ["/bin/sh", "-c"]
        args:
          - >-
            pg_dump -h postgres -U $(POSTGRES_USER) -d $(POSTGRES_DB) -Fc > /backup/$(date +%Y-%m-%d-%H%M).dump &&
            echo "Backup completed"
        envFrom:
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: backup-volume
          mountPath: /backup
      restartPolicy: Never
      volumes:
      - name: backup-volume
        persistentVolumeClaim:
          claimName: postgres-backup-pvc 