FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o kids-api ./cmd/api

FROM gcr.io/distroless/static-debian11:latest

WORKDIR /
COPY --from=builder /app/kids-api /kids-api
COPY --from=builder /app/internal/migrations /migrations

EXPOSE 8080
USER nonroot:nonroot

ENTRYPOINT ["/kids-api"]